---
title: "Projects"
---

A place to keep some links of publicly accessible mini-projects. The vast majority of my work is unfortunately proprietary. Since coming across Quarto in the autumn of 2023, my intention is to keep educational coding examples within this space for future reference.

-   [Quarto initiation](https://seanvw.github.io/Hello_Quarto/ "Quarto initiation")

-   [Linear Mixed-Effect Models examples](https://seanvw.github.io/Linear_Mixed_Effect_Models_2/ "Linear Mixed-Effect Models examples")

-   [RNA Seq Analysis examples](https://seanvw.github.io/RNA_Analysis/ "RNA Seq Analysis examples")

-   [Dashboard examples with Quarto](https://seanvw.github.io/Dashboards/ "Dashboard examples with Quarto")

-   [Dash and similar](https://seanvw.github.io/Dash/ "Dash and similar")

-   [WGS Bacteria](https://seanvw.github.io/WGS_Bacteria/ "WGS Bacteria")

-   [Insertional mutagenesis — interactive saturation simulation](https://seanvw.github.io/mutagenesis/ "Insertional mutagenesis — interactive saturation simulation")




And, some links directly into GitHub

-   [LabKey evaluation](https://github.com/seanvw/Egs_LabKey/blob/main/README.md)

-   [Example(s), Artificial Neural Network with Python](https://github.com/seanvw/Ann_Egs/blob/main/ANN_Fit_Multi_Var_Models_v01.ipynb)

-   [Google Cloud Platform](https://cloud.google.com/?hl=en)

-   [BigQuery - Looker Studio - Gemini integration](https://github.com/seanvw/GCP_Egs/blob/main/README.md)

-   [ApexAI, AutoML, BQML](https://github.com/seanvw/vertex-ai-mlops-sw/blob/main/readme.md)

-   [Claude DB REST API, UI and MCP server ](https://github.com/seanvw/claude_db_api_1)

-   PySR, High-Performance Symbolic Regression in Python and Julia

...
